name = "ardaudiothek-dl"
uuid = "d491c8dc-ac5d-4f58-8d4e-d258e8d936ed"
authors = ["Frederik Banning <frederik.banning@ruhr-uni-bochum.de>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
